#!/bin/bash

if [ -z "$1" ] && [ -z "$2" ]; then
    echo "Usage: bigfiles [path] [results(int)]"
else
    du -a $1 \
        | sort -n -r \
        | head -n $2 \
        | awk '{split("KB- MB- GB-",v);s=1;while($1>1024){$1/=1024;s++} print int($1) v[s] $2}'
fi
